### ISSUE TITLE
What's the correct way to patch an id? 

### ISSUE THREAD

**Issue by thinktt** [Vincit/objection.js#100]
I noticed when I try to patch and change a value in an idColumn Objection takes the value out of the query. In other words I can't change anything in column if it is set as the idColumn (as far as I can tell).

I am working around this by changing the idColumn when I'm doing a patch, but this is kind of hacky. Is there a better way to do this? Is there a reason why it is set up this way that I should be aware of? 

Appreciate the library and your time!

**Comment by koskimas** [comment]
Yeah, patch and update remove the `idColumn` from the update. The reasoning was "who would ever want to change the id" :smile:, but I quess that was stupid. This may be a bug more than a feature...

You can always use knex and skip the objection query layer like this:
```
Person.knexQuery().update({id: 1000, foo: 200}).where('id', 1000)
```

**Comment by thinktt** [comment]
Awesome, the knexQuery trick helps, I might use that. I appreciate it!

**Comment by fl0w** [comment]
Depending on how you want to handle this @koskimas I think [this](https://github.com/Vincit/objection.js/blob/master/src/queryBuilder/operations/UpdateOperation.js#L28) is the source for this bug/feature.

Want me to try and attack this one or are you perhaps still contemplating about this one?

**Comment by newhouse** [comment]
Hi @koskimas -Firstly, thanks again to you and all contributors for the great work you're doing on this project. I really like it a lot! 👍 👏 

I'm also experiencing the same problem and found this github Issue while about to submit one. It took me a while to decide that it was an issue with Objection vs. Knex, as my issue was encountered on a Model with a composite key, so I thought maybe that had something to do with it, but now I think not.

Perhaps my scenario will convince you of why it may be better to remove this "feature", so I'll elaborate:

- I have a table `invitations` that allows Users to invite people to join their Organization in my app.
- `invitations` has a composite _natural_ key: `organiation_id` + `email`, so I didn't create some unnecessary surrogate key.
- In the `Invitation` model I created in Objection, I specify the `idColumn` property to return `['organization_id', 'email']`
- If a User would like to update the `email` (or, heck, the `organization_id`) field for an invitation, they should be allowed to do that.
- The following code should patch the `email` field, but it doesn't:
```
let orgId = 12345;
let existingEmail = 'joe@dirt.com';
let newEmail = 'joe@mamma.com';

Invitation
  .query()
  .patchAndFetchById([orgId, existingEmail], { email: newEmail })
  .then(...)
  .catch(...)
```
- While dropping down into `Invitation.knexQuery()` will get the job done, I believe it sidesteps all validation for the properties in the patch object, which is less-than-desirable.

Hopefully this bug can be revisited and corrected?

**Comment by koskimas** [comment]
Thanks!

That is actually a really good point. You've convinced me!

This will be a breaking change, so you'll have to wait for 0.7. There will probably be a beta/rc version with this fix earlier. Also I'm going on a trip for a month, so not much will probably happen this year.

**Comment by koskimas** [comment]
Fixed in 0.7.0-rc.1

**Comment by jdolearydl** [comment]
@koskimas I'm still experiencing this bug in 0.9.2
`Question.query().updateAndFetchById(70, {abbreviation: 2})`
```
ERROR:  syntax error at or near "where" at character 24
update "question" set  where "question"."id" = $1
```
