### ISSUE TITLE
Incorrect type for Model class createNotFoundError static method

### ISSUE THREAD

**Issue by eijiew** [Vincit/objection.js#1984]
https://github.com/Vincit/objection.js/blob/73e27d00a6e0ca2ef8e5c43b6214898139183530/typings/objection/index.d.ts#L1588

Hi the types for `Model.createNotFoundError` seems to be missing 2 arguments?

Should it be `static createNotFoundError(ctx: QueryContext, args: CreateNotFoundErrorArgs): Error;`

**Comment by koskimas** [comment]
I fixed this yesterday.

**Comment by eijiew** [comment]
I see the fix for interface `ModelClass` in v2.2.10. But its still missing for class `Model`. Or am I mistaken?

**Comment by koskimas** [comment]
Shit! You're right. I'll fix that asap and release v2.2.11

**Comment by koskimas** [comment]
Fixed in 2af79111a51044c088d0c862015013e28c371e17
