### ISSUE TITLE
Add esm module support

### ISSUE THREAD

**Issue by vladshcherbin** [Vincit/objection.js#2023]
Hey 👋 

Node 12+ supports esm modules, Node 10 end of life is in April which means we can stop using babel, bundlers, etc in node 🥳
Package maintainers are starting to publish new package versions with only esm modules support, e.g. `sindresorhus` with 1k+ packages is going this road ([article](https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77)).

It would be great to see esm module support in objection. Currently some imports/exports don't work:

```js
// works
import { Model } from 'objection'`
console.log(Model)

// doesn't work - throws error
import { snakeCaseMappers } from 'objection'

// works - current workaround
import objection from 'objection'
console.log(objection.snakeCaseMappers)
```

Produced error (node v15.12.0):

```console
SyntaxError: Named export 'snakeCaseMappers' not found. The requested module 'objection' is a CommonJS module,
which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'objection';
const { snakeCaseMappers } = pkg;
```

Since 3.0 is coming with knex 0.95 support, maybe this can be also added in major release.

Thank you 🤗

**Comment by koskimas** [comment]
`Model` and `snakeCaseMappers` are exported identically. Here's the code

```js
module.exports = {
  Model,
  QueryBuilder,
  QueryBuilderBase,
  QueryBuilderOperation,
  RelationExpression,
  ValidationError,
  NotFoundError,
  AjvValidator,
  Validator,
  Relation,
  HasOneRelation,
  HasManyRelation,
  BelongsToOneRelation,
  HasOneThroughRelation,
  ManyToManyRelation,

  transaction,
  initialize,
  compose,
  mixin,
  ref,
  val,
  raw,
  fn,

  get lit() {
    deprecate('`lit` is deprecated. Use `val` instead. `lit` will be removed in 3.0');
    return val;
  },

  snakeCaseMappers,
  knexSnakeCaseMappers,
  knexIdentifierMapping,

  ...DbErrorClasses,
};
```

Do you have any idea why one would work, but not the other?

**Comment by vladshcherbin** [comment]
@koskimas yep, I've also checked current exports and around 85% are present as esm. The error message has `may not support all module.exports as named exports` part but I have no idea how it re-exports only some of them.

**Comment by koskimas** [comment]
Do all after the `lit` getter fail?

**Comment by vladshcherbin** [comment]
@koskimas I believe yes.

<details>
 <summary>List of exports (import * as objection from 'objection')</summary>

```js
[Module: null prototype] {
  AjvValidator: [Function: AjvValidator],
  BelongsToOneRelation: [class BelongsToOneRelation extends Relation],
  HasManyRelation: [class HasManyRelation extends Relation],
  HasOneRelation: [class HasOneRelation extends HasManyRelation],
  HasOneThroughRelation: [class HasOneThroughRelation extends ManyToManyRelation],
  ManyToManyRelation: [class ManyToManyRelation extends Relation],
  Model: [Function: Model] { QueryBuilder: [Function: QueryBuilder] },
  NotFoundError: [class NotFoundError extends Error],
  QueryBuilder: [Function: QueryBuilder],
  QueryBuilderBase: [class QueryBuilderBase extends QueryBuilderOperationSupport],
  QueryBuilderOperation: [class QueryBuilderOperation],
  Relation: [class Relation],
  RelationExpression: [class RelationExpression],
  ValidationError: [class ValidationError extends Error],
  Validator: [Function: Validator],
  compose: [Function: compose],
  default: {
    Model: [Function: Model] { QueryBuilder: [Function: QueryBuilder] },
    QueryBuilder: [Function: QueryBuilder],
    QueryBuilderBase: [class QueryBuilderBase extends QueryBuilderOperationSupport],
    QueryBuilderOperation: [class QueryBuilderOperation],
    RelationExpression: [class RelationExpression],
    ValidationError: [class ValidationError extends Error],
    NotFoundError: [class NotFoundError extends Error],
    AjvValidator: [Function: AjvValidator],
    Validator: [Function: Validator],
    Relation: [class Relation],
    HasOneRelation: [class HasOneRelation extends HasManyRelation],
    HasManyRelation: [class HasManyRelation extends Relation],
    BelongsToOneRelation: [class BelongsToOneRelation extends Relation],
    HasOneThroughRelation: [class HasOneThroughRelation extends ManyToManyRelation],
    ManyToManyRelation: [class ManyToManyRelation extends Relation],
    transaction: [Function: transaction] { start: [Function (anonymous)] },
    initialize: [AsyncFunction: initialize],
    compose: [Function: compose],
    mixin: [Function: mixin],
    ref: [Function: ref],
    val: [Function: val],
    raw: [Function: raw],
    fn: [Function: fn] {
      coalesce: [Function (anonymous)],
      concat: [Function (anonymous)],
      sum: [Function (anonymous)],
      avg: [Function (anonymous)],
      min: [Function (anonymous)],
      max: [Function (anonymous)],
      count: [Function (anonymous)],
      upper: [Function (anonymous)],
      lower: [Function (anonymous)],
      now: [Function (anonymous)]
    },
    lit: [Getter],
    snakeCaseMappers: [Function: snakeCaseMappers],
    knexSnakeCaseMappers: [Function: knexSnakeCaseMappers],
    knexIdentifierMapping: [Function: knexIdentifierMapping],
    DBError: [class DBError extends Error],
    UniqueViolationError: [class UniqueViolationError extends ConstraintViolationError],
    NotNullViolationError: [class NotNullViolationError extends ConstraintViolationError],
    ForeignKeyViolationError: [class ForeignKeyViolationError extends ConstraintViolationError],
    ConstraintViolationError: [class ConstraintViolationError extends DBError],
    CheckViolationError: [class CheckViolationError extends ConstraintViolationError],
    DataError: [class DataError extends DBError]
  },
  fn: [Function: fn] {
    coalesce: [Function (anonymous)],
    concat: [Function (anonymous)],
    sum: [Function (anonymous)],
    avg: [Function (anonymous)],
    min: [Function (anonymous)],
    max: [Function (anonymous)],
    count: [Function (anonymous)],
    upper: [Function (anonymous)],
    lower: [Function (anonymous)],
    now: [Function (anonymous)]
  },
  get: undefined,
  initialize: [AsyncFunction: initialize],
  mixin: [Function: mixin],
  raw: [Function: raw],
  ref: [Function: ref],
  transaction: [Function: transaction] { start: [Function (anonymous)] },
  val: [Function: val]
}
```

</details>

**Comment by koskimas** [comment]
Ok, thanks. I thought I know what's wrong. I'll fix this for 3.0

**Comment by slewsys** [comment]
Just a heads up: attempting to import models also fails, e.g.:

**Comment by koskimas** [comment]
Should be fixed in master now.

**Comment by lehni** [comment]
While `knexSnakeCaseMappers`now seems to work in 3.0.0, `CheckViolationError` & co. (all the error classes from the `db-errors` package) still can't be imported from objection. I can create a test-case if needed, but maybe it's a trivial fix?

We should probably check the full list here: https://github.com/Vincit/objection.js/issues/2023#issuecomment-806059039

**Comment by spengilley** [comment]
@slewsys Could you tell me how you worked around this problem please?
