### ISSUE TITLE
TypeScript 4.7 Upgrade results in "Type instantiation is excessively deep and possibly infinite."

### ISSUE THREAD

**Issue by laurisvan** [Vincit/objection.js#2277]
This is a followup to issue #1668, which seems to resurface with the latest TypeScript (4.7 RC1) upgrade.

Queries of type
```
await this.$query()
  .patch({
    ...update
  })
  .returning('*')
```

Result in TS error `TS2589: Type instantiation is excessively deep and possibly infinite.`.

It appears it is related to this.$query() type of queries, and particularly to `.returning('*')`. The model class used in the app is of type `export class WorkPlan extends RescommsModel` (where RescommsModel is of type `export class RescommsModel extends Model`), but it appears that inheriting directly from Objection Model does not make any difference.

**Comment by laurisvan** [comment]
Note: This might well be specific to the fact TypeScript 4.7 being a release candidate and still having some bugs, but I wonder if somebody more versed in TypeScript complex type inference could tell if that were the case.

**Comment by niteshrawat1995** [comment]
@laurisvan  Did you manage to solve this?

**Comment by laurisvan** [comment]
My PR #2278 seems to solve the issue.

**Comment by niteshrawat1995** [comment]
Any updates?

**Comment by hrmcdonald** [comment]
Been running into this same issue as well. Specifically when using `returning(*)` from a `$query()`.

**Comment by keepcosmos** [comment]
any update or any news here?

**Comment by joshkay** [comment]
Running into this issue as well.  Anyone have a solution?

**Comment by keepcosmos** [comment]
Same thing happens with typescript 4.7.x.
But the issue is no longer reproduced in typesciprt 4.8.3. seems to have been resolved.

**Comment by falkenhawk** [comment]
> Same thing happens with typescript 4.7.x. But the issue is no longer reproduced in typesciprt 4.8.3. seems to have been resolved.

unfortunately, no change in my case in typescript 4.8.3, still getting same amount of `TS2589: Type instantiation is excessively deep and possibly infinite.` errors, as in 4.7.3

**Comment by ahilke** [comment]
> But the issue is no longer reproduced in typesciprt 4.8.3. seems to have been resolved.

I'm also encountering this issue with latest typescript 4.9.5. Occurs in a query using both `first()` as well as `returning(*)`.

**Comment by lehni** [comment]
Could somebody provide a reproducible example similar to the one provided in https://github.com/Vincit/objection.js/issues/2132#issuecomment-962988859

I have tried to reproduce this issue but have failed. This may be working now due to the change in 2cefc7735a67a6a840952c407d2a4589cc4d77ba

If somebody could test and confirm, or provide an example if the problem remains, that would be great, thanks!

**Comment by ahilke** [comment]
Hi @lehni, I am still experiencing this issue with the latest versions, i.e. `objection@3.0.2` and `typescript@5.0.4`. I realised my example was not sufficient, apologies. I've created a reproduction repository here: https://github.com/ahilke/objection-reproduce-2277

**Comment by lehni** [comment]
@ahilke I wasn't talking of the latest released version. I have since merged some TS fixes and am curious to see if they help with this. Could you install objection from master in your repo and test? e.g. following https://www.pluralsight.com/guides/install-npm-packages-from-gitgithub

**Comment by ahilke** [comment]
@lehni Oh, sorry, didn't realise those changes were not released yet. I've installed `master` (commit 9b92eb11d1f9278d4c58f0cfb820757f9e65eeea), but still experience the same error. Updated the repo accordingly.

**Comment by lehni** [comment]
Alright, thanks for the heads up! I'd say let's merge this and be done with it :)

**Comment by klesgidis** [comment]
This still happens to me with ts 4.9.5

**Comment by johnnyshankman** [comment]
For the record, I was getting issues with this when downgrading a version of knex to match my objection version after realizing i had version conflicts.

The source of the error was not because of a typescript nor an objection/knex versions issue per say. 

It was an obtuse error surrounding a type error in my calls to things like `insert()` and `insertAndFetch()`

### Before

```
const snapshot = await AudienceSnapshot.query().insert({
      name,
      // ....
      // @note: causes error of "Type instantiation is excessively deep and possibly infinite." 
      timestamp: someDateTimeString,
 });
 ```
 
 ### After
 
 ```
 const snapshot = await AudienceSnapshot.query().insert({
      name,
      // ...
      // @note: objection expects a JS Date not a datetime string here
      timestamp: new Date(timestamp),
});
```
