### ISSUE TITLE
upsertGraph with compound key in relation

### ISSUE THREAD

**Issue by mattboutet** [Vincit/objection.js#517]
It appears that in some cases upsertGraph isn't inserting rows.  Example:

My Preferences model was set up with table.primary(['userId', 'category']) and below is what I'm trying:
```javascript
const prefs = [{ category: 'sms', setting: 'off' }, { category: 'sound', setting: 'off' }];
Users.query().upsertGraph({ id: user.id, preferences }).asCallback((err, updated) => {

    console.log(updated);
});
```
Will log:
```
Users {
  id: 23,
  preferences: 
   [ Preferences { category: 'sms', setting: 'nope', userId: 23 },
     Preferences { category: 'loudNoises', setting: 'nope', userId: 23 } ] }
```
If there's nothing in the table, then adding a `debug()` to the builder chain will show that 2 `select`s are being generated, but no `insert`/`update`s.  If there's data in the table, anything not contained in the `preferences` array will be deleted, but nothing gets inserted.

It could be that, because we already have the primary key (`['userId', 'category']`) it's not trying to do the insert but because the row doesn't exist, it's not trying to update?

**Comment by koskimas** [comment]
Normally when a row has an id, and it is not found, an error is thrown saying something like

```
model (id=100,200) is not a child of model (id=1,1). If you want to relate it, use the relate: true option
```
(this error may have been added after the version you are using)

We need a way to tell `upsertGraph` to insert the ones that are not found instead of throwing that error. 

Maybe something like:
```js
const prefs = [{ category: 'sms', setting: 'off' }, { category: 'sound', setting: 'off' }];
Users
  .query()
  .upsertGraph(
    { id: user.id, preferences }, 
    { insertMissing: true }
  )
  .asCallback((err, updated) => {
    console.log(updated);
  });
```

Any thoughts?

**Comment by koskimas** [comment]
Actually in your specific case, you only provide half of the id explicitly and therefore it should be treated as an insert. Could you try the HEAD version to see if this particular case is already fixed?

**Comment by mattboutet** [comment]
Thanks for the quick turnaround on this!

I just `npm link`ed in Master to try this out, and I'm still seeing the same behavior.

I think an `insertMissing` flag is a fine solution.  It's a pretty niche issue, so I don't see any problem in requiring an explicit flag there.

**Comment by koskimas** [comment]
I'm trying to reproduce your case. Is `preferences` a `HasManyRelation` or a `ManyToManyRelation`?

**Comment by koskimas** [comment]
Actually could you send me the `relationMapping`

**Comment by koskimas** [comment]
I just wrote this and it works...

```js
  describe('upsertGraph with compound key in relation #403', () => {
    let knex = session.knex;
    let Users;
    let Preferences;

    before(() => {
      return knex.schema
        .dropTableIfExists('Users')
        .dropTableIfExists('Preferences')
        .createTable('Users', table => {
          table.integer('id').primary();
        })
        .createTable('Preferences', table => {
          table.integer('userId');
          table.string('category');
          table.string('setting');
          table.primary(['userId', 'category']);
        });
    });

    after(() => {
      return knex.schema
        .dropTableIfExists('Preferences')
        .dropTableIfExists('Users');
    });

    before(() => {
      Users = class Users extends Model {
        static get tableName() {
          return 'Users';
        }

        static get relationMappings() {
          return {
            preferences: {
              relation: Model.HasManyRelation,
              modelClass: Preferences,
              join: {
                from: 'Preferences.userId',
                to: 'Users.id'
              }
            }
          };
        }
      };

      Preferences = class Preferences extends Model {
        static get tableName() {
          return 'Preferences';
        }

        static get idColumn() {
          return ['userId', 'category'];
        }
      }

      Users.knex(knex);
      Preferences.knex(knex);
    });

    before(() => {
      return Users.query().insert({
        id: 1
      })
    });

    it('test', () => {
      const preferences = [{ category: 'sms', setting: 'off' }, { category: 'sound', setting: 'off' }];

      return Users
        .query()
        .debug()
        .upsertGraph(
          { id: 1, preferences }
        )
        .then(updated => {
          return Users.query().eager('preferences');
        })
        .then(updated => {
          console.log(updated);
        });
    });

  });
```

**Comment by koskimas** [comment]
@mattboutet Could you take a look at the test I wrote and tell me what's different from your setup? My test works and yours doesn't.

**Comment by mattboutet** [comment]
Thanks for digging into this @koskimas, I'll have time to explore a bit deeper later this week, but a quick copy/paste of the actual test body above into my project shows that I'm still seeing the behavior with PostgreSQL.

The `debug()` above logs:
```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: 'd2eab30c-a520-4bbf-8389-0d5b38ef437a',
  sql: 'select "Users"."id" from "Users" where "Users"."id" in (?)' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '9a3c33ed-e030-46b6-8449-bdba5b24c0a7',
  sql: 'select "Preferences"."userId", "Preferences"."category" from "Preferences" where "Preferences"."userId" in (?)' }
```

It's definitely possible that the issue could lie elsewhere in my project, but the db schema appear to be the same, so I'll need to spend a bit more time digging into this, which I won't really have until later in the week.

**Comment by koskimas** [comment]
Any progress?

**Comment by mattboutet** [comment]
`1e3530a` has fixed the issue for me.  Thanks so much for getting to the bottom of this one.

**Comment by koskimas** [comment]
Awesome!
